pub enum TokenType {
    IntLiteral,
    UIntLiteral,
    CharLiteral,
    StrLiteral,
    DoubleLiteral,
    BooleanLiteral,
    IntKeyword,
    UIntKeyword,
    CharKeyword,
    StrKeyword,
    DoubleKeyword,
    BooleanKeyword,
    Dec,
    Fn,
    Ret,
    Semicolon,
    OpeningPar,
    ClosingPar,
    OpeningCur,
    ClosingCur,
    OpeningBra,
    ClosingBra,
    OpeningQuo,
    ClosingQuo,
    OpeningDiv,
    ClosingDiv,
    Equal,
    GreaterEqual,
    Greater,
    SmallerEqual,
    Smaller,
    Minus,
    Plus,
    Multi,
    Div,
    Comma,
    Colon
}

pub struct Token {
    pub Type: TokenType,
    pub Data: Option<String>,
}